#ifndef __ACRN_CONFIG_H__
#define __ACRN_CONFIG_H__
#define CONFIG_BOARD "qemu"

#include <asm/defconfig.h>
#include <asm/board.h>
#define CONFIG_MAX_IOAPIC_NUM 1U
#define CONFIG_MAX_IOAPIC_LINES 120U
#define CONFIG_MAX_MSIX_TABLE_NUM 64U
#define CONFIG_SCENARIO "shared"
#define CONFIG_MEM_LOGLEVEL_DEFAULT 5U
#define CONFIG_NPK_LOGLEVEL_DEFAULT 5U
#define CONFIG_CONSOLE_LOGLEVEL_DEFAULT 5U
#define CONFIG_SERIAL_LEGACY 1
#define CONFIG_SERIAL_PIO_BASE 0x3F8U
#define CONFIG_SCHED_NOOP 1
#define CONFIG_UC_LOCK_DETECTION_ENABLED 1
#define CONFIG_ACPI_PARSE_ENABLED 1
#define CONFIG_MCE_ON_PSC_WORKAROUND_ENABLED 1
#define CONFIG_RELOC 1
#define CONFIG_MULTIBOOT2 1
#define CONFIG_HV_RAM_START 0x11000000U
#define CONFIG_HV_RAM_SIZE 0x5600000U
#define ACFG_MAX_PCI_BUS_NUM 0x7U
#define CONFIG_MAX_PCI_DEV_NUM 96U
#define CONFIG_MAX_PT_IRQ_ENTRIES 64U
#define CONFIG_IGD_SBDF 0xFFFFU
#define CONFIG_GUEST_KERNEL_BZIMAGE 1

#define NR_CPUS CONFIG_NR_CPUS
#endif
